version: '3'
services:
  homer:
    image: b4bz/homer:latest
    platform: linux
    ports:
      - "8902:8080/tcp"
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/Homer/assets:/www/assets
      - /portainer/Files/AppData/Config/Homer:/www/config.yml
